### ISSUE TITLE
undefined method `map' for "":String Did you mean? tap

### ISSUE THREAD

**Issue by atbyrd** [neo4jrb/neo4j#1334]
When visiting a page my rails application it get the following error. I also get the same error when running `rake neo4j:migrate:all`

> undefined method `map' for "":String Did you mean? tap

##### Extracted source (around line #62):
```
list = response.body || []
            list.map do |item|
              {type: CONSTRAINT_TYPES[item[:type]],
               label: item[:label].to_sym,
               properties: item[:property_keys].map(&:to_sym)}
```

##### trace

```
> neo4j-core (7.0.0) lib/neo4j/core/cypher_session/adaptors/http.rb:62:in `constraints'
> neo4j-core (7.0.0) lib/neo4j/core/cypher_session.rb:36:in `block (2 levels) in <class:CypherSession>'
> neo4j-core (7.0.0) lib/neo4j/core/label.rb:100:in `constraints'
> neo4j-core (7.0.0) lib/neo4j/core/label.rb:124:in `constraint?'
> neo4j (8.0.1) lib/neo4j/migrations/runner.rb:17:in `initialize'
> neo4j (8.0.1) lib/neo4j/migrations.rb:13:in `new'
> neo4j (8.0.1) lib/neo4j/migrations.rb:13:in `check_for_pending_migrations!'
> neo4j (8.0.1) lib/neo4j/migrations/check_pending.rb:13:in `call'
> actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
> activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
> activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
> activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
> actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
> actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
> actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
> actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
> web-console (3.4.0) lib/web_console/middleware.rb:135:in `call_app'
> web-console (3.4.0) lib/web_console/middleware.rb:28:in `block in call'
> web-console (3.4.0) lib/web_console/middleware.rb:18:in `catch'
> web-console (3.4.0) lib/web_console/middleware.rb:18:in `call'
> actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
> railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
> railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
> activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
> activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
> activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
> railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
> sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
> actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
> rack (2.0.1) lib/rack/method_override.rb:22:in `call'
> rack (2.0.1) lib/rack/runtime.rb:22:in `call'
> activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
> actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
> actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
> rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
> railties (5.0.1) lib/rails/engine.rb:522:in `call'
> puma (3.6.2) lib/puma/configuration.rb:225:in `call'
> puma (3.6.2) lib/puma/server.rb:578:in `handle_request'
> puma (3.6.2) lib/puma/server.rb:415:in `process_client'
> puma (3.6.2) lib/puma/server.rb:275:in `block in run'
> puma (3.6.2) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

###### migration

```
class Candidate < Neo4j::Migrations::Base
  def up
    add_constraint :Candidate, :uuid
  end

  def down
    drop_constraint :Candidate, :uuid
  end
end
```

###### candiate.rb

```
class Candidate
  include Neo4j::ActiveNode
  #
  # Neo4j.rb needs to have property definitions before any validations. So, the property block needs to come before
  # loading your devise modules.
  #
  # If you add another devise module (such as :lockable, :confirmable, or :token_authenticatable), be sure to
  # uncomment the property definitions for those modules. Otherwise, the unused property definitions can be deleted.
  #

  property :username, type: String
  property :facebook_token, type: String
  index :facebook_token

  property :created_at, type: DateTime
  property :updated_at, type: DateTime

  ## Database authenticatable
  property :email, type: String, default: ''
  index :email

  property :encrypted_password

  ## If you include devise modules, uncomment the properties below.

  ## Rememberable
  property :remember_created_at, type: DateTime
  property :remember_token
  index :remember_token

  ## Recoverable
  property :reset_password_token
  index :reset_password_token
  property :reset_password_sent_at, type: DateTime

  ## Trackable
  property :sign_in_count, type: Integer, default: 0
  property :current_sign_in_at, type: DateTime
  property :last_sign_in_at, type: DateTime
  property :current_sign_in_ip, type: String
  property :last_sign_in_ip, type: String

  ## Confirmable
  # property :confirmation_token
  # index :confirmation_token
  # property :confirmed_at, type: DateTime
  # property :confirmation_sent_at, type: DateTime

  ## Lockable
  #  property :failed_attempts, type: Integer, default: 0
  # property :locked_at, type: DateTime
  #  property :unlock_token, type: String,
  # index :unlock_token

  ## Token authenticatable
  # property :authentication_token, type: String, null: true, index: :exact

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
end

```

**Comment by atbyrd** [comment]
### Update

After restarting my machine and installing neo4j using brew instead of the rake task I get  a new error.

`no implicit conversion of Symbol into Integer
`
```
list = response.body || []
            list.map do |item|
              {type: CONSTRAINT_TYPES[item[:type]],
               label: item[:label].to_sym,
               properties: item[:property_keys].map(&:to_sym)}
            end
```

**Comment by cheerfulstoic** [comment]
Thanks for the report @atbyrd !

I've actually been working on some fixes to the model generator in this PR to the `devise-neo4j` gem:

https://github.com/neo4jrb/devise-neo4j/pull/28

One of the biggest changes is that Neo4j models as of 8.0 (just released last week) should no longer have `index` calls inside of them (but I also fixed a number of other small details).

Could you try it again by including the following line in your `Gemfile` and re-generating your `Candidate` model?

```ruby
gem 'devise-neo4j', github: 'neo4jrb/devise-neo4j', branch: 'fixing_model_generator'
```

That may fix your problem.

I haven't merged the PR because the specs are failing, but the specs have started failing on `master` anyway since the last run a year ago, so I might just need to release a new version anyway if things work well for you.

**Comment by atbyrd** [comment]
@cheerfulstoic I'm still getting the same error. Even after destroying my models and migrations and regenerating them.

**Comment by cheerfulstoic** [comment]
Ah, shoot, I knew I'd seen this before.  Seems like [this](https://github.com/neo4jrb/devise-neo4j/issues/27) might be the same issue.  Looking at it now

**Comment by cheerfulstoic** [comment]
I think I've fixed this (or at least made it better).  There was an issue where Neo4j was returning an error when the gem was trying to get constraints or indexes which was simply causing the gem's code to trip up.  That error should now be raised as an exception.  Try running:

```ruby
bundle update neo4j neo4j-core
```

At that point you *should* get a `CypherSession::ConnectionFailedError` exception with more information from Neo4j on what is wrong

**Comment by atbyrd** [comment]
This seem to help. Except I had to comment out a line in the migration     `# add_index :<%= table_name %>, :reset_password_token, force: true`

**Comment by cheerfulstoic** [comment]
Oh, interesting that the `<%= table_name %>` was left in there.  I need to figure out how to render that ERB template to put the model's label in there.  Thanks for pointing that out!

**Comment by cheerfulstoic** [comment]
Thanks again, I just released `devise-neo4j` 2.1.1 which should fix this issue

**Comment by cheerfulstoic** [comment]
That is a bit odd.  Did you specify gems with `bundle update`?  You could do `bundle update activesupport` or maybe `bundle update activesupport neo4j` to update both gems at the same time.

**Comment by atbyrd** [comment]
@cheerfulstoic I've tried all approaches to updating the gems

**Comment by cheerfulstoic** [comment]
;( I'm not sure what it would be then.  I just looked at the `gemspec` again and I don't know what might cause that from the `neo4j` gem.

As a test if you're using RVM you could maybe try creating another gemset (maybe another version of Ruby?) so that everything is fresh...

**Comment by atbyrd** [comment]
@cheerfulstoic Not sure whats going on but running `bundle exec rake neo4j:migrate:all` works.

Thanks

**Comment by cheerfulstoic** [comment]
Interesting!  Sometimes if you've got a number of versions of gems in your environment things can get confused unless you use `bundle exec` to make sure that the right gems for your project are being used.

Glad you got it working!

**Comment by atbyrd** [comment]
I'm still getting the same original exception when trying to run migrations.

**Comment by cheerfulstoic** [comment]
By that error, do you mean `undefined method `map' for "":String Did you mean? tap`?  If so, which version of the `neo4j-core` gem is in your `Gemfile`?  Also, are you using `bundle exec` for the migrations (otherwise, it might be using an old version of the gem)?

**Comment by atbyrd** [comment]
I'm using `8.0.5` and running `bundle exec rake neo4j:migrate:all` gives the same error.

**Comment by cheerfulstoic** [comment]
Ok, interesting.  I wonder if you could help gather a bit more info.  If you run this command:

```ruby
EDITOR=atom bundle neo4j-core
```

That will open the copy of the `neo4j` gem that rubygems has copied down for you so you should be able to edit files and see the results.  I made the assumption that you're using the Atom editor, but you can put in another editor if you like.

If you edit that file at the top of the backtrace and output `response.body` that should hopefully give us some more context on what is going on.

If you're using Rails you might be using spring, which caches the state of the gems that you are using which means that updates to the `neo4j-core` gem won't apply unless you run this first:

```
spring stop
```
